
	CR = 13
	

	;### ACORN ###
	
	;OSRDRM=&FFB9
	;OSEVEN=&FFBF
	;GSINIT=&FFC2
	;GSREAD=&FFC5
	;NVWRCH=&FFC8
	;NVRDCH=&FFCB
	OSFIND = $FFCE
	OSGBPB = $FFD1
	OSBPUT = $FFD4
	OSBGET = $FFD7
	OSARGS = $FFDA
	OSFILE = $FFDD
	;OSRDCH=&FFE0
	;OSASCI=&FFE3
	;OSNEWL=&FFE7
	;OSWRCH=&FFEE
	OSWORD = $FFF1
	OSBYTE = $FFF4
	;OSCLI=&FFF7
	
	TK_STOP = $70 OR $80
	TK_RVS = $60 OR $80

	
	RAMBOTTOM = $100	;BOTTOM OF RAM FOR USE BY BASIC
	RAMTOP = $102		;TOP OF RAM FOR USE BY BASIC

	; SCREEN RAM

	SRAM = $5CD8
	
	; SYSTEM VIA TIMERS (USED BY BASIC RND)
	
	CHTIM = $FE44

	; USER VIA TIMERS
	
	ORG $FE64	; T1 TIMER USED BY EDITOR SCROLL ROUTINE

.TIL	SKIP 1
.TIH	SKIP 1
.TILL	SKIP 1
.TILH	SKIP 1
.T2L	SKIP 1
.T2H	SKIP 1
.SR		SKIP 1
.ACR	SKIP 1
.PCR	SKIP 1
.IFR	SKIP 1
.IER	SKIP 1



	; ### DSPLY ENTRY POINTS ###
	
	ORG $0900
	
;.RESET
	JMP &FFFF
;.TRAP
	JMP &FFFF
.CURSON
	JMP &FFFF
.CURSOFF
	JMP &FFFF
.POKEVIA
	JMP &FFFF
	
	
	; KEY CODES

	K_STOP = $03
	K_RUN = $83
	K_DOWN = $11
	K_UP = $11
	K_RVSON = $12
	K_RVSOFF = $12
	K_HOME = $13
	K_CLR = $13
	K_DEL = $14
	K_INST = $14
	K_RIGHT = $1D
	K_LEFT = $1D
	
	
	; BASIC
	
	LINLEN	=40
	FORSIZ	=18
	BUFLEN	=81
	ADDPRC	=1
	STKEND	=507	; STACK END $1FB
	CLMWID	=10
	XPI	=255
	NUMLEV	=23
	STRSIZ	=3
	;RAMLOC = 1024

	
	; ### ZERO PAGE ###

	ORG $0000
	
.USRPOK			SKIP 1

.USRADD			SKIP 1
				SKIP 1

.INTEGR
.CHARAC			SKIP 1
.ENDCHR			SKIP 1
.COUNT			SKIP 1
.DIMFLG			SKIP 1
.VALTYP			SKIP 1
.INTFLG			SKIP 1
.GARBFL
.DORES			SKIP 1
.SUBFLG			SKIP 1
.INPFLG			SKIP 1
.DOMASK
.TANSGN			SKIP 1
.CNTWFL			SKIP 1
.CHANNL			SKIP 1
.LINWID			SKIP 1
.NCMWFL			SKIP 1
.POKER
.LINNUM			SKIP 2
.TEMPPT			SKIP 1
.LASTPT			SKIP 2
.TEMPST			SKIP 9
.INDEX
.INDEX1			SKIP 2
.INDEX2			SKIP 2
.RESHO			SKIP 1
.RESMOH			SKIP 1
.ADDEND
.RESMO			SKIP 1
.RESLO			SKIP 2

.TXTTAB			SKIP 2
.VARTAB			SKIP 2
.ARYTAB			SKIP 2
.STREND			SKIP 2
.FRETOP			SKIP 2
.FRESPC			SKIP 2
.MEMSIZ			SKIP 2
.CURLIN			SKIP 2
.OLDLIN			SKIP 2
.OLDTXT			SKIP 2
.DATLIN			SKIP 2
.DATPTR			SKIP 2
.INPPTR			SKIP 2
.VARNAM			SKIP 2
.FDECPT
.VARPNT			SKIP 2
.LSTPNT
.ANDMSK
.FORPNT			SKIP 1
.EORMSK			SKIP 1
.VARTXT
.OPPTR			SKIP 2
.OPMASK			SKIP 1
.GRBPNT
.TEMPF3
.DEFPNT			SKIP 2
.DSCPNT			SKIP 2
.STRLEN			SKIP 1
.FOUR6			SKIP 1
.JMPER			SKIP 1
.SIZE			SKIP 1
.OLDOV			SKIP 1
.TEMPF1			SKIP 1
.ARYPNT
.HIGHDS			SKIP 2
.HIGHTR			SKIP 2
.TEMPF2			SKIP 1
.DECCNT
.LOWDS			SKIP 1
.TENEXP			SKIP 1
.GRBTOP
.DPTFLG
.LOWTR			SKIP 1
.EXPSGN			SKIP 1
.DSCTMP
.FAC
.FACEXP			SKIP 1
.FACHO			SKIP 1
.FACMOH			SKIP 1
.INDICE
.FACMO			SKIP 1
.FACLO			SKIP 1
.FACSGN			SKIP 1
.DEGREE
.SGNFLG			SKIP 1
.BITS			SKIP 1
.ARGEXP			SKIP 1
.ARGHO			SKIP 1
.ARGMOH			SKIP 1
.ARGMO			SKIP 1
.ARGLO			SKIP 1
.ARGSGN			SKIP 1
.STRNG1
.ARISGN			SKIP 1
.FACOV			SKIP 1

.BUFPTR
.STRNG2
.POLYPT
.CURTOL
.FBUFPT			SKIP 2

.CHRGET			SKIP 6
.CHRGOT			SKIP 1
.TXTPTR			SKIP 6
.QNUM			SKIP 10
.CHRRTS			SKIP 1
.RNDX			SKIP 5


	; EDITOR / KERNAL

.CTIMR
.TIME		SKIP 3		;24 HR CLOCK IN 1/60 SEC;

.VFLAG		SKIP 1		;UPDATE DISPLAY

.INDX			SKIP 2	;
.LSXP			SKIP 1	;START GF SCREEN INPUT
.LSTP			SKIP 1	;
.CRSW			SKIP 1	;INPUT/GET FLAG
.PNT			SKIP 2
.TRMPOS	;BASIC
.PNTR			SKIP 1	; CURSOR HPOS
.SAL			SKIP 1	; TEMP PTR USED BY EDITOR
.SAH			SKIP 1
.QTSW			SKIP 1
.LNMX			SKIP 1	; MAX LENGTH OF LINE
.TBLX			SKIP 1	; CURSOR VPOS
.DATAX			SKIP 1
.INSRT			SKIP 1


	ORG $0400
	
.VECTAB			; VECTOR TABLE

	ORG $0420

	; FILING

.FBLK					;OSFILE BLOCK
.FNADR			SKIP 2	;ADDRESS OF FILENAME
.STAL			SKIP 1	;LOAD ADDRESS
.STAH			SKIP 3
.FEXA			SKIP 4	;EXECUTION ADDRESS (SET FIRST BYTE TO ZERO WHEN LOADING)
.FLEN
.FSTAL			SKIP 1	;SAVE START ADDRESS (AFTER LOAD LENGTH OF FILE)
.FSTAH			SKIP 3
.EAL			SKIP 1	;SAVE END ADDRESS
.EAH			SKIP 3

;.FNLEN			SKIP 1	;LENGTH CURRENT FILE N STR
;.LA				SKIP 1	;CURRENT FILE LOGICAL ADDR
.SA				SKIP 1	;CURRENT FILE 2ND ADDR
.FA				SKIP 1	;CURRENT FILE PRIMARY ADDR


	; EDITOR

.LDTB1	SKIP 25+2	; LINE WRAP FLAGS (BIT 7)
IF NOT(ROMTAB)
.LDTB2	SKIP 25
.LDTB3	SKIP 25
ENDIF
.KEYD	SKIP 11		; KEYBOARD BUFFER

.NDX	SKIP 1		;INDEX TO KEYD QUEUE
.RVS	SKIP 1		;REVERSE FIELD ENABLED
.SFDX	SKIP 1		;SHIFT MODE FOR PRINT

.CSTAT	;BASIC
.SATUS	SKIP 1		;OPERATION STATUS BYTE
.DFLTN	SKIP 1		;DEFAULT INPUT DEVICE #
.DFLTO	SKIP 1		;DEFAULT QUTPUT DEVICE #



	ORG $0500

	;BASIC INPUT BUFFER

			; NOTE 4 BYTES :  BUF-1,BUF-2,BUF-3,BUF-4 (LINK & LINE# ?)
.SAVNAM				;BUFFER	
.BUF	SKIP 81	;MUST START AT BEGINING OF PAGE!

	BUFPAG	=HI(BUF)

	ORG $057F
	
.LOFBUF			SKIP 1	;BASIC	;ORIGINALLY AT $00FF
.FBUFFR					;BASIC 	;ORIGINALLY AT $0100 (HOW BIG DOES THIS NEED TO BE?)


	\\ END OF FILE
	
	
	

	



