

MACRO HOP1
	EQUB &24	; BIT ZP (I.E SKIP NEXT 1 BYTE INSTRUCTION)
ENDMACRO

MACRO HOP2
	EQUB &2C	; BIT ABS (I.E SKIP NEXT 2 BYTE INSTRUCTION)
ENDMACRO

MACRO XSTR A$	; STRING ENDS WHEN BIT 7 SET
	L = LEN(A$)
	IF L > 1
		EQUS LEFT$(A$,L-1)
	ENDIF
	EQUS ASC(RIGHT$(A$,1)) OR &80
	PRINT A$
ENDMACRO



